export default class colors {
    static colorPrimary = "#00A4C8";
    static colorPrimaryDark = "#6AC603";
    static colorPrimaryLight = "#6AC603";
    static colorAccent = "rgba(255, 255, 255, 0.2)";
    static colorBlack = "#000000";
    static colorWhite = "#fefefe";
    static colorPurple = "#8b0afd";
    static colorFacebookBlue = "#4267B2";
    static colorGoogleBlue = "#4285F4";
    static colorOrange = "#ff9019";
    static colorOpacityOrange = "#fef8f4";
    static colorOpacityPrimary = "#87CEEB";
    static colorOpacityXLightGray = "rgba(242,243,245,0.49)";
    static colorOpacityWhite = 'rgba(255, 255, 255, 0.8)';
    static colorOpacityGreen = '#6AC60396';
    static colorOpacityBlack = "rgba(52, 52, 52, 0.5)";
    static colorTextXDarkGray = "#292828";
    static colorXDarkGray = "#292828";
    static colorDarkGray = "#6c6969";
    static colorGray = "#A2A4A4";
    static colorLightGray = "#cfcaca";
    static colorXLightGray = "#F2F3F5";
    static colorXLightBlue = "#e6eaee";
    static colorRed = "#FF0000";
    static colorGreen = "#008000";
    static colorSecondGreen = '#59af04'
    static colorDarkSkyBlue = "#35a1f4";
    static colorWhatsappGreen = "#4FCE5D";
    static colorLightGreen = "#ecf8e1";
    static colorLightBlack = "#28292d";
    static colorBackgroundGray = "#f8f8fa";
    static colorBackgroundBlue= '#f4f4ff';
    static colorHeadingBlack = "#030303";
    static colorRedBrown = "#c44242";
    static colorSecondGreen = "#0fba47";
    static colorBorderGray = '#e9e9eb';
    static colorEditGray = '#757678';
    static colorTransparent = '#ffffff00';
    static colorThirdGreen = '#61ad14';
    static colorChatBgWhite = '#fafafa'
}
