import { Dimensions, PixelRatio } from 'react-native';
import DeviceInfo from 'react-native-device-info';

const { width, height } = Dimensions.get('window');
export default {
  _width8per: width * 0.08,
  _width10per: width * 0.1,
  _width20per: width * 0.2,
  _width30per: width * 0.3,
  _width35per: width * 0.35,
  _width40per: width * 0.4,
  _width50per: width * 0.5,
  _width55per: width * 0.55,
  _width60per: width * 0.6,
  _width70per: width * 0.7,
  _width72per: width * 0.72,
  _width80per: width * 0.8,
  _width90per: width * 0.9,
  _width100per: width,
  _heightDrawerAndroid: height * 0.964,
  _heightDrawerIOS: height,
  _height10per: height * 0.10,
  _height11per: height * 0.114,
  _height15per: height * 0.15,
  _height17per: height * 0.17,
  _height20per: height * 0.20,
  _height22per: height * 0.22,
  _height24per: height * 0.24,
  _height25per: height * 0.25,
  _height26per: height * 0.27,
  _height30per: height * 0.3,
  _height35per: height * 0.35,
  _height40per: height * 0.4,
  _height70per: height * 0.75,
  _height100per: height,
  _iosShadowOpacity: 0.35,
  _iosShadowRadius: 16,
  _iosShadowWidth: 0,
  _iosShadowHeight: 8,
  _iosKeyboardOffset: 64,
  _iosStatusBarHeight: DeviceInfo.hasNotch() ? 30 : 10,
  _iosBottomBarHeight: DeviceInfo.hasNotch() ? 34 : 0,
  _iosBottomNavigationBarHeightHome: DeviceInfo.hasNotch()
    ? PixelRatio.roundToNearestPixel(90)
    : PixelRatio.roundToNearestPixel(60),
  _iosToolbarHeight: DeviceInfo.hasNotch()
    ? PixelRatio.roundToNearestPixel(110)
    : PixelRatio.roundToNearestPixel(80),
  _iosToolbarSecondaryHeight: DeviceInfo.hasNotch()
    ? PixelRatio.roundToNearestPixel(220)
    : PixelRatio.roundToNearestPixel(180),
  _iosToolbarHeightHome: DeviceInfo.hasNotch()
    ? PixelRatio.roundToNearestPixel(140)
    : PixelRatio.roundToNearestPixel(110),
  _iosNavigationDrawerHeaderHeight: DeviceInfo.hasNotch()
    ? PixelRatio.roundToNearestPixel(140)
    : PixelRatio.roundToNearestPixel(100),
  _iosNavigationDrawerBottomPadding: DeviceInfo.hasNotch() ? 34 : 20,
  _0_5sdp: PixelRatio.roundToNearestPixel(0.5),
  _1sdp: PixelRatio.roundToNearestPixel(1),
  _2sdp: PixelRatio.roundToNearestPixel(2),
  _3sdp: PixelRatio.roundToNearestPixel(3),
  _5sdp: PixelRatio.roundToNearestPixel(5),
  _6sdp: PixelRatio.roundToNearestPixel(6),
  _7sdp: PixelRatio.roundToNearestPixel(7),
  _8sdp: PixelRatio.roundToNearestPixel(8),
  _9sdp: PixelRatio.roundToNearestPixel(9),
  _10sdp: PixelRatio.roundToNearestPixel(10),
  _12sdp: PixelRatio.roundToNearestPixel(12),
  _14sdp: PixelRatio.roundToNearestPixel(14),
  _15sdp: PixelRatio.roundToNearestPixel(15),
  _16sdp: PixelRatio.roundToNearestPixel(16),
  _17sdp: PixelRatio.roundToNearestPixel(17),
  _18sdp: PixelRatio.roundToNearestPixel(18),
  _19sdp: PixelRatio.roundToNearestPixel(19),
  _20sdp: PixelRatio.roundToNearestPixel(20),
  _22sdp: PixelRatio.roundToNearestPixel(22),
  _25sdp: PixelRatio.roundToNearestPixel(25),
  _30sdp: PixelRatio.roundToNearestPixel(30),
  _35sdp: PixelRatio.roundToNearestPixel(35),
  _40sdp: PixelRatio.roundToNearestPixel(40),
  _45sdp: PixelRatio.roundToNearestPixel(45),
  _50sdp: PixelRatio.roundToNearestPixel(50),
  _60sdp: PixelRatio.roundToNearestPixel(60),
  _70sdp: PixelRatio.roundToNearestPixel(70),
  _80sdp: PixelRatio.roundToNearestPixel(80),
  _90sdp: PixelRatio.roundToNearestPixel(90),
  _100sdp: PixelRatio.roundToNearestPixel(100),
  _110sdp: PixelRatio.roundToNearestPixel(110),
  _120sdp: PixelRatio.roundToNearestPixel(120),
  _130sdp: PixelRatio.roundToNearestPixel(130),
  _135sdp: PixelRatio.roundToNearestPixel(135),
  _140sdp: PixelRatio.roundToNearestPixel(140),
  _150sdp: PixelRatio.roundToNearestPixel(150),
  _160sdp: PixelRatio.roundToNearestPixel(160),
  _175sdp: PixelRatio.roundToNearestPixel(175),
  _180sdp: PixelRatio.roundToNearestPixel(180),
  _200sdp: PixelRatio.roundToNearestPixel(200),
  _220sdp: PixelRatio.roundToNearestPixel(220),
  _260sdp: PixelRatio.roundToNearestPixel(260),
  _280sdp: PixelRatio.roundToNearestPixel(280),
  _300sdp: PixelRatio.roundToNearestPixel(300),
  _minus5sdp: PixelRatio.roundToNearestPixel(-5),
  _minus10sdp: PixelRatio.roundToNearestPixel(-10),
  _minus30sdp: PixelRatio.roundToNearestPixel(-30),
  largeTxt: PixelRatio.roundToNearestPixel(24),
  extraLargeTxt: PixelRatio.roundToNearestPixel(30),
  semiLargeText: PixelRatio.roundToNearestPixel(20),
  regularTxt: PixelRatio.roundToNearestPixel(16),
  smallTxt: PixelRatio.roundToNearestPixel(14),
  microTxt: PixelRatio.roundToNearestPixel(12),
};
